Name: CronManager
Version: dev-master
Link: https://github.com/Webiny/CronManager
Description: Manage your cron jobs using a user friendly UI
Author:
    Name: Webiny LTD
    Email: info@webiny.com
    Link: https://www.webiny.com